[project]
name = "pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "pymupdf4llm>=0.0.27",
    "pypdf>=6.0.0",
    "streamlit>=1.49.1",
]
